In [100]:
import numpy as np
import torch
from scipy.linalg import sqrtm

In [101]:
from torch.autograd import Variable

In [102]:
x = Variable( torch.tensor([.8]), requires_grad=True )

In [103]:
x

tensor([0.8000], requires_grad=True)

In [104]:
def f(x):
    return np.exp(x.detach)

In [105]:
z = f(x)

AttributeError: 'builtin_function_or_method' object has no attribute 'exp'

In [65]:
z

tensor([0.2621], grad_fn=<PowBackward0>)

In [66]:
z.backward()

In [67]:
x.grad

tensor([1.9661])

In [60]:
6*.8**5

1.9660800000000005

In [54]:
3*.8**2

1.9200000000000004

In [68]:
x

tensor([0.8000], requires_grad=True)

In [83]:
y = torch.tensor([1.0], requires_grad=True)

In [84]:
y

tensor([1.], requires_grad=True)

In [91]:
np.exp(y)

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [93]:
np.exp(y.detach())

tensor([2.7183])